djoserauthapi/urls.py
# Import necessary modules
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.contrib import admin
from django.contrib.staticfiles import views
# Import external packages
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView

# Import my packages
from .views import  CustomTokenObtainPairView

# Define URL patterns for authentication using djoser and social authentication
urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('auth/', include('djoser.social.urls')),
    path('admin/', admin.site.urls),
    path('', include('folder.urls', namespace='main')),
    path('folder/', include('folder.urls', namespace='folder')),
    path('file/', include('file.urls', namespace='file')),
# urls.py
    path('api/token/', CustomTokenObtainPairView.as_view(),name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [
        re_path(r'^.*', TemplateView.as_view(template_name='index.html')),
        re_path(r'^static/(?P<path>.*)$', views.serve),
        re_path(r'^(?P<path>.*)$', views.serve),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
 # add at the last
# urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

file/urls.py
from django.urls import path
from file import views
from .views import get_tags, create_tag

app_name = 'file'


urlpatterns = [
    path('add/', views.FileCreateView.as_view(), name='add'),
    path('list/', views.FileListView.as_view(), name='list'),
    path('<int:pk>/download/', views.FileDownloadView.as_view(), name='download'),
    path('delete/<int:pk>/', views.FileDeleteView.as_view(), name='file_delete'),
    path('get_tags/', get_tags, name='get_tags'),
    path('create_tag/', create_tag, name='create_tag'),
    path('edit_tag/<int:pk>/', views.TagUpdateView.as_view(), name='edit_tag'),
    path('delete_tag/<int:pk>/', views.TagDeleteView.as_view(), name='delete_tag'),
    path('update/<int:pk>/', views.FileUpdateView.as_view(), name='file_update'),
    path('api/files/<int:pk>/{pdf-url}/', views.get_pdf_url, name='get_pdf_url'),

]

folder/urls.py
from django.urls import path
from folder import views
from .views import get_csrf_token

app_name = 'folder'

urlpatterns = [
    path('add/', views.FolderCreateView.as_view(), name='add'),
    path('list/', views.FolderListView.as_view(), name='list'),
    path('details/<int:folder_id>/', views.FolderDetailsView.as_view(), name='details'),
    path('<int:folder_id>/file/<int:pk>/delete/', views.FileDeleteView.as_view(), name='file-delete'),
    path('edit/<int:pk>/', views.FolderUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.FolderDeleteView.as_view(), name='delete'),
    path('get-csrf-token/', get_csrf_token, name='get_csrf_token'),
    path('details/<int:folder_id>/subfolders/', views.FolderDetailsSubfoldersView.as_view(), name='details_subfolders'),
    path('details/<int:folder_id>/edit/<int:subfolder_id>/', views.FolderDetailsEditView.as_view(), name='details_edit'),
    path('details/<int:folder_id>/delete/<int:subfolder_id>/', views.FolderDetailsDeleteView.as_view(), name='details_delete'),
]

file/models.py
from django.db import models
from django.urls import reverse

from folder.models import Folder
from taggit.managers import TaggableManager
from taggit.models import TagBase, GenericTaggedItemBase

class ColorTag(TagBase):
    color = models.CharField(max_length=50, blank=True, null=True)

# Define a custom TaggedItem model with a ForeignKey to your File model
class ColorTaggedItem(GenericTaggedItemBase):
    tag = models.ForeignKey(ColorTag, on_delete=models.CASCADE, related_name="%(app_label)s_%(class)s_items")

class File(models.Model):
    name = models.CharField(max_length=128)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE, null=True, blank=True)
    file = models.FileField(upload_to='documents/')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    tags = TaggableManager(through=ColorTaggedItem)


    def __str__(self):
        return f'{self.name}'

    @property
    def get_download_url(self):
        return reverse('file:download', args=[self.pk])

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.name:
            self.name = self.file.name
        return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)

    @property
    def full_path(self):
        return f'{self.folder}::{self.name}'

    @property
    def extension(self):
        return str(self.name).split('.')[-1]

    @property
    def icon(self):
        if self.extension == 'txt':
            return '-alt'
        elif self.extension == 'pdf':
            return '-pdf'
        elif self.extension in ['doc', 'docs', 'docx', 'odt', 'dot', 'dotm', 'dotx']:
            return '-word'
        elif self.extension in ['xls', 'xlsx', 'xlt']:
            return '-excel'
        elif self.extension in ['ppt', 'pptx', 'ppsx']:
            return '-powerpoint'
        elif self.extension in ['png', 'jpg', 'jpeg']:
            return '-image'
        elif self.extension in ['mp4', 'mkv', 'flv', 'vob', 'avi', 'wmv']:
            return '-video'
        elif self.extension in ['mp3', 'aa', 'aac', 'act', 'mmf', 'mpc']:
            return '-audio'
        elif self.extension in ['py', 'js', 'java', 'php', 'rb', 'html', 'css', 'htm']:
            return '-code'
        elif self.extension in ['zip', 'rar', 'iso', '7z', 'apk']:
            return '-archive'
        elif self.extension == 'csv':
            return '-csv'
        else:
            return ''

folder/models.py
from django.db import models
from django.urls import reverse


class Folder(models.Model):
    name = models.CharField(max_length=128)
    text_color = models.CharField(max_length=32, default='#000000', blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        full_name = f'{self.name}'
        if self.parent:
            full_name = f'{self.parent}::' + full_name
        return full_name

    @property
    def depth(self):
        if not self.parent:
            return 0
        else:
            return self.parent.depth + 1

    @property
    def get_list_url(self):
        return reverse('folder:list')

    def parent_url(self):
        url_list = []
        temp = self
        while(temp.parent):
            temp = temp.parent
            url_list.append(reverse('folder:list') + '?id=' + str(temp.pk))

        return url_list

folder/forms.py
from django.forms import ModelForm

from folder.models import Folder


class FolderForm(ModelForm):
    class Meta:
        model = Folder
        fields = ['name', 'text_color', 'parent']

folder/views.py
from django.urls import reverse
from django.views.generic import ListView, CreateView
from django.views import View
from folder.forms import FolderForm
from folder.models import Folder
from file.forms import FileForm
from file.models import File
# folder/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from file.models import File
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from folder.models import Folder
from folder.forms import FolderForm
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from folder.models import Folder
from django.http import JsonResponse
from django.middleware.csrf import get_token
from rest_framework.decorators import api_view
@api_view(['GET'])
def get_csrf_token(request):
    csrf_token = get_token(request)
    return JsonResponse({'csrf_token': csrf_token})
class FolderDeleteView(DeleteView):
    model = Folder
    template_name = 'folder/confirm_folder_delete.html'
    success_url = reverse_lazy('folder:list')
class FolderUpdateView(UpdateView):
    model = Folder
    form_class = FolderForm
    template_name = 'folder/edit.html'
    success_url = reverse_lazy('folder:list')
class FileDeleteView(DeleteView):
    model = File
    success_url = reverse_lazy('folder:list')
class FolderCreateView(CreateView):
    form_class = FolderForm
    template_name = 'folder/add.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_url'] = reverse('folder:add')
        context['add_folder'] = reverse('folder:add')
        context['add_file'] = reverse('file:add')
        return context
    def get_success_url(self):
        return reverse('folder:list')
class FolderListView(ListView):
    def get_queryset(self):
        pk = self.request.GET.get('id')
        queryset = Folder.objects.all()
        if pk:
            queryset = queryset.filter(parent__pk=pk)
        else:
            queryset = queryset.filter(parent=None)
        order_by = self.request.GET.get('sort')
        if order_by == 'time':
            queryset = queryset.order_by('-created_at')
        elif order_by == 'name':
            queryset = queryset.order_by('name')
        return queryset
    def get_file_query(self, pk):
        file_query = File.objects.all()
        if pk:
            file_query = file_query.filter(folder__pk=pk)
        else:
            file_query = file_query.filter(folder=None)
        order_by = self.request.GET.get('sort')
        if order_by == 'time':
            file_query = file_query.order_by('-created_at')
        elif order_by == 'name':
            file_query = file_query.order_by('name')
        return file_query
    @staticmethod
    def get_parent_folder_link(pk):
        parent_folder = []
        if pk:
            folder = Folder.objects.get(pk=pk)
            parent_folder.append({
                'text': folder.name,
                'link': reverse('folder:list') + f'?id={folder.pk}',
            })
            while folder.parent:
                parent_folder.append({
                    'text': folder.parent.name,
                    'link': reverse('folder:list') + f'?id={folder.parent.pk}',
                })
                folder = folder.parent
            parent_folder.reverse()
        return parent_folder
    def render_to_response(self, context, **response_kwargs):
        pk = self.request.GET.get('id')
        folder_list = [
            {'id': folder.id, 'name': folder.name} for folder in self.get_queryset()
        ]
        file_list = [
            {'id': file.id, 'name': file.name} for file in self.get_file_query(pk)
        ]
        parent_folder = [
            {'text': folder['text'], 'link': folder['link']} for folder in self.get_parent_folder_link(pk)
        ]
        response_data = {
            'folder_list': folder_list,
            'file_list': file_list,
            'parent_folder': parent_folder,
        }
        return JsonResponse(response_data)
class FolderDetailsView(View):
    def get(self, request, folder_id):
        try:
            folder = Folder.objects.get(pk=folder_id)
            subfolders = Folder.objects.filter(parent=folder)
            files = File.objects.filter(folder=folder)
            folder_list = [{'id': subfolder.id, 'name': subfolder.name} for subfolder in subfolders]
            file_list = [{'id': file.id, 'name': file.name} for file in files]
            response_data = {
                'folder_list': folder_list,
                'file_list': file_list,
                'parent_folder': [],  # You can implement this if needed
            }
            return JsonResponse(response_data)
        except Folder.DoesNotExist:
            return JsonResponse({'error': 'Folder not found'}, status=404)
class FolderDetailsSubfoldersView(View):
    def get(self, request, folder_id):
        try:
            folder = Folder.objects.get(pk=folder_id)
            subfolders = Folder.objects.filter(parent=folder)
            folder_list = [{'id': subfolder.id, 'name': subfolder.name} for subfolder in subfolders]
            response_data = {
                'folder_list': folder_list,
            }
            return JsonResponse(response_data)
        except Folder.DoesNotExist:
            return JsonResponse({'error': 'Folder not found'}, status=404)
class FolderDetailsEditView(View):
    def post(self, request, folder_id, subfolder_id):
        try:
            subfolder = get_object_or_404(Folder, pk=subfolder_id, parent__pk=folder_id)
            form = FolderForm(request.POST, instance=subfolder)
            if form.is_valid():
                subfolder.name = form.cleaned_data['name']  # Update only the 'name' field
                subfolder.save(update_fields=['name'])  # Save the updated subfolder
                return JsonResponse({'message': 'Subfolder name updated successfully'})
            else:
                return JsonResponse({'error': 'Invalid form data'}, status=400)
        except Folder.DoesNotExist:
            return JsonResponse({'error': 'Subfolder not found'}, status=404)
class FolderDetailsDeleteView(View):
    def post(self, request, folder_id, subfolder_id):
        try:
            # Assuming subfolder_id is a valid ID for the subfolder
            subfolder = Folder.objects.get(pk=subfolder_id, parent__id=folder_id)
            subfolder.delete()
            return JsonResponse({'message': 'Subfolder deleted successfully'})
        except Folder.DoesNotExist:
            return JsonResponse({'error': 'Subfolder not found'}, status=404)

folder/templates/folder/add.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block css %}{% endblock %}

{% block content %}
<div class="ml40 mt40">
  <h4 class="text-muted mb30">Create New Folder</h4>
  <form method="post" novalidate>
    {% comment %} {% csrf_token %} {% endcomment %}

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {% for error in form.non_field_errors %}
          {{ error }}
        {% endfor %}
      </div>
    {% endif %}

    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.label_tag }}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}
      </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

{% block js %}
<script>

</script>
{% endblock %}

folder/templates/folder/confirm_folder_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Confirm Folder Deletion</h2>
    <p>Are you sure you want to delete the folder "{{ folder.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'folder:list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

folder/templates/folder/edit.html
{% extends 'base.html' %}

{% block content %}
  <h4 class="text-muted mb-4">Edit Folder</h4>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
  <a href="{% url 'folder:list' %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

folder/templates/folder/list.html
{% extends 'base.html' %}

{% block css %}
<!-- Add any CSS specific to this template if needed -->
{% endblock %}

{% block content %}
<div class="container ml20 mt-3">
    <p class="text-muted">Folders</p>
    <div class="row">
        {% for folder in folder_list %}
        <li>
            <a href="{{ folder.get_list_url }}?id={{ folder.pk }}" class="">
                <div class="card card-style">
                    <div class="card-body">
                        <h6 class="card-title"><i class="fas fa-folder"></i>
                            <span style="color: {{ folder.text_color }};" class="ml20">
                                {{ folder.name|truncatechars:18 }}
                            </span>
                        </h6>
                        <a href="{% url 'folder:edit' folder.pk %}" class="btn btn-warning">Edit</a>
                        <a href="{% url 'folder:delete' folder.pk %}" class="btn btn-danger">Delete</a>
                    </div>
                </div>
            </a>
        </li>
        {% empty %}
            <p class="text-muted ml40">Sorry, no folders here.</p>
        {% endfor %}
    </div>
</div>

<div class="container ml20 mt-3">
    <p class="text-muted">Files</p>
    <div class="row">
        {% for file in file_list %}
            <div class="card card-style">
                <div class="card-body">
                    <!-- Display file information -->
                    <p class="card-text"><small class="text-muted">
                        This is a wider card with supporting text below as a natural lead-in to additional content.
                    </small></p>
                    <h6 class="card-title">
                        <i class="fas fa-file{{ file.icon }}"></i>
                        <span class="ml5 mr15">{{ file.name|truncatechars:17 }}</span>
                        
                        <!-- Display file tags as labels -->
                        {% for tag in file.tags.all %}
                            <span class="badge badge-info">{{ tag }}</span>
                        {% endfor %}
                        
                        <span class="float-right">
                            <a href="{{ file.get_download_url }}"><i class="fas fa-download"></i></a>
                            <a href="{% url 'file:file-delete' file.pk %}" class="btn btn-danger">Delete</a>
                        </span>
                    </h6>
                </div>
            </div>
        {% empty %}
            <p class="text-muted ml40">Sorry, no files in this folder.</p>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

{% block js %}
<!-- Add any JavaScript specific to this template if needed -->
{% endblock %}